export const DESTINOS = [
  {
    slug: "iquitos",
    nombre: "Iquitos",
    etiqueta: "La puerta de la Amazonía",
    imagen: "iquits.jpg",
    intro: "Una ciudad viva entre los ríos Amazonas, Nanay e Itaya.",
    descripcion: "Iquitos combina historia, gastronomía amazónica y una vida marcada por el río. Es nuestro principal punto de llegada y una gran puerta para descubrir la selva peruana.",
    ruta: "Conexión fluvial desde Requena y los puertos intermedios.",
    destacados: ["Malecón y paseo ribereño", "Mercados y sabores amazónicos", "Punto de partida para conocer la selva"],
    viaje: "Desde Iquitos puedes conectar con Requena, Nauta y comunidades del río.",
    coord: [-3.7491, -73.2516],
    tiempo: "Desde Requena, alrededor de 6 horas por río.",
    mejorEpoca: "Clima cálido y húmedo todo el año (25–33 °C). En creciente (noviembre–mayo) el río está alto; en vaciante (junio–octubre) aparecen las playas.",
    gastronomia: ["Juane", "Tacacho con cecina", "Patarashca de pescado", "Refresco de cocona y aguaje"],
    queLlevar: ["Repelente de insectos", "Protector solar y gorra", "Poncho o impermeable", "Efectivo (poco acceso a cajeros)"],
    festividades: [
      { nombre: "Carnaval Amazónico", fecha: "Febrero", mes: "FEB" },
      { nombre: "Fiesta de San Juan", fecha: "24 de junio", dia: "24", mes: "JUN" },
      { nombre: "Virgen de la Natividad", fecha: "8 de septiembre", dia: "08", mes: "SEP" },
    ],
  },
  {
    slug: "requena",
    nombre: "Requena",
    etiqueta: "La Atenas del Ucayali",
    imagen: "Requena2025.jpg",
    intro: "Nuestra central, a orillas del río Ucayali.",
    descripcion: "Requena es una ciudad ribereña con una identidad muy ligada a la navegación. Aquí se encuentra nuestra central y el punto de partida de los viajes que acercan personas, carga y comunidades.",
    ruta: "Central de Transportes Rayza y salida de rutas fluviales.",
    destacados: ["Plaza y vida urbana ribereña", "Puerto y movimiento fluvial", "Hotel, restaurante y servicios Rayza"],
    viaje: "Compra tu pasaje desde Requena y elige el tramo que necesitas recorrer.",
    coord: [-5.0553, -73.8514],
    tiempo: "Central de la empresa y punto de partida de todas las rutas.",
    mejorEpoca: "Ciudad ribereña de clima cálido todo el año. Buen punto de partida en cualquier temporada del río.",
    gastronomia: ["Juane de gallina", "Inchicapi", "Pescado a la parrilla", "Chapo de plátano"],
    queLlevar: ["Repelente de insectos", "Protector solar", "Ropa ligera y cómoda", "Documento de identidad"],
    festividades: [
      { nombre: "Fiesta de San Juan", fecha: "24 de junio", dia: "24", mes: "JUN" },
      { nombre: "Aniversario de Requena", fecha: "18 – 23 de agosto", dia: "23", mes: "AGO" },
      { nombre: "Fiesta patronal", fecha: "Octubre", mes: "OCT" },
    ],
  },
  {
    slug: "nauta",
    nombre: "Nauta",
    etiqueta: "Puerto de conexión",
    imagen: "nauta.jpg",
    intro: "Un punto de encuentro entre ríos, historia y carretera.",
    descripcion: "Nauta es una de las ciudades históricas de Loreto y un puerto clave para moverse por la Amazonía. Su cercanía a Iquitos y a las grandes rutas fluviales la convierte en una parada importante para viajeros y comerciantes.",
    ruta: "Parada de conexión en la ruta fluvial de la región.",
    destacados: ["Laguna Sapi Sapi", "Puerto y malecón", "Acceso por carretera desde Iquitos"],
    viaje: "Consulta las salidas disponibles y reserva con anticipación para tu tramo hacia o desde Nauta.",
    coord: [-4.5083, -73.5831],
    tiempo: "A una hora y media de Iquitos por carretera; también conectada por río.",
    mejorEpoca: "Cálido y húmedo todo el año. Cerca de la unión de los ríos Marañón y Ucayali, origen del Amazonas.",
    gastronomia: ["Pescado fresco de río", "Juane", "Tacacho", "Frutas amazónicas"],
    queLlevar: ["Repelente de insectos", "Protector solar y gorra", "Agua", "Efectivo"],
    festividades: [
      { nombre: "Aniversario de Nauta", fecha: "30 de abril", dia: "30", mes: "ABR" },
      { nombre: "Fiesta patronal San Felipe y Santiago", fecha: "Mayo", mes: "MAY" },
      { nombre: "Fiesta de San Juan", fecha: "24 de junio", dia: "24", mes: "JUN" },
    ],
  },
  {
    slug: "jenaro-herrera",
    nombre: "Jenaro Herrera",
    etiqueta: "Comunidad del río Ucayali",
    imagen: "jherrera.jpg",
    intro: "Un destino ribereño conectado por la ruta de los pueblos del río.",
    descripcion: "Jenaro Herrera forma parte de los puertos que enlazan las comunidades de la provincia de Requena. El viaje por río es parte de su día a día y una forma especial de conocer la vida amazónica.",
    ruta: "Parada intermedia de las rutas que recorren el Ucayali.",
    destacados: ["Paisaje ribereño", "Vida de comunidad", "Conexión con puertos cercanos"],
    viaje: "Selecciona tu origen y destino al comprar: puedes viajar por tramos, no solo hasta el puerto final.",
    coord: [-4.9056, -73.6686],
    tiempo: "Parada intermedia entre Requena e Iquitos, sobre el río Ucayali.",
    mejorEpoca: "Clima cálido y húmedo todo el año. Sede de un centro de investigación de la Amazonía.",
    gastronomia: ["Pescado de río", "Juane", "Plátano y yuca", "Frutas de la zona"],
    queLlevar: ["Repelente de insectos", "Protector solar", "Poncho o impermeable", "Efectivo"],
    festividades: [
      { nombre: "Fiesta de San Juan", fecha: "24 de junio", dia: "24", mes: "JUN" },
      { nombre: "Feria Agropecuaria y Artesanal", fecha: "27 – 29 de julio", dia: "27", mes: "JUL" },
    ],
  },
];

export function buscarDestino(slug) {
  return DESTINOS.find((destino) => destino.slug === slug);
}
